version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/emergallery

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_NAME
            yarn deploy

  deploy:
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - run:
          name: Deploy to Firebase
          command: |
            cd ./firebase/functions
            yarn install
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN


workflows:
  version: 2
  emergallery:
    jobs:
      - build
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy
          filters:
            branches:
              ignore:
                - gh-pages
